services:
  - type: web
    name: pharmacy-project-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx http-server dist/pharmacy-project -p 10000 --spa
    envVars:
      - key: NODE_VERSION
        value: 18
